// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: mesh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRole int32

const (
	AgentRole_OPERATIONAL AgentRole = 0 // NATS-based fast path
	AgentRole_STRATEGIC   AgentRole = 1 // gRPC-based reasoning path
)

// Enum value maps for AgentRole.
var (
	AgentRole_name = map[int32]string{
		0: "OPERATIONAL",
		1: "STRATEGIC",
	}
	AgentRole_value = map[string]int32{
		"OPERATIONAL": 0,
		"STRATEGIC":   1,
	}
)

func (x AgentRole) Enum() *AgentRole {
	p := new(AgentRole)
	*p = x
	return p
}

func (x AgentRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRole) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[0].Descriptor()
}

func (AgentRole) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[0]
}

func (x AgentRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRole.Descriptor instead.
func (AgentRole) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

type OSResources struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent  float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes  uint64                 `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskIoWait       float64                `protobuf:"fixed64,4,opt,name=disk_io_wait,json=diskIoWait,proto3" json:"disk_io_wait,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OSResources) Reset() {
	*x = OSResources{}
	mi := &file_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSResources) ProtoMessage() {}

func (x *OSResources) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSResources.ProtoReflect.Descriptor instead.
func (*OSResources) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *OSResources) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *OSResources) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *OSResources) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *OSResources) GetDiskIoWait() float64 {
	if x != nil {
		return x.DiskIoWait
	}
	return 0
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	InitialRole   AgentRole              `protobuf:"varint,3,opt,name=initial_role,json=initialRole,proto3,enum=mesh.AgentRole" json:"initial_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HandshakeRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HandshakeRequest) GetInitialRole() AgentRole {
	if x != nil {
		return x.InitialRole
	}
	return AgentRole_OPERATIONAL
}

type HandshakeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Approved       bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ResourceLimits *OSResources           `protobuf:"bytes,4,opt,name=resource_limits,json=resourceLimits,proto3" json:"resource_limits,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HandshakeResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *HandshakeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HandshakeResponse) GetResourceLimits() *OSResources {
	if x != nil {
		return x.ResourceLimits
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CurrentLoad   *OSResources           `protobuf:"bytes,3,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	CurrentRole   AgentRole              `protobuf:"varint,4,opt,name=current_role,json=currentRole,proto3,enum=mesh.AgentRole" json:"current_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Heartbeat) GetCurrentLoad() *OSResources {
	if x != nil {
		return x.CurrentLoad
	}
	return nil
}

func (x *Heartbeat) GetCurrentRole() AgentRole {
	if x != nil {
		return x.CurrentRole
	}
	return AgentRole_OPERATIONAL
}

type AgentAction struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AgentId    string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ActionType string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // e.g. "OS_COMPILATION", "REASONING", "SEARCH"
	// Strict parameters for known OS operations
	ResourceImpact *OSResources `protobuf:"bytes,3,opt,name=resource_impact,json=resourceImpact,proto3" json:"resource_impact,omitempty"`
	// The JSON Flex-Layer: for unmodeled task data/self-programming
	Payload *structpb.Struct `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Strategic reasoning context (populated when in Strategic role)
	ReasoningChain string `protobuf:"bytes,5,opt,name=reasoning_chain,json=reasoningChain,proto3" json:"reasoning_chain,omitempty"`
	// Intent declaration for predictive throttling (AgentCgroup)
	TaskIntent string `protobuf:"bytes,6,opt,name=task_intent,json=taskIntent,proto3" json:"task_intent,omitempty"`
	// --- Phase 7: ScheInfer Hints ---
	DataSizeBytes uint64 `protobuf:"varint,7,opt,name=data_size_bytes,json=dataSizeBytes,proto3" json:"data_size_bytes,omitempty"` // Size of the tensor/data to be processed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAction) Reset() {
	*x = AgentAction{}
	mi := &file_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAction) ProtoMessage() {}

func (x *AgentAction) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAction.ProtoReflect.Descriptor instead.
func (*AgentAction) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *AgentAction) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *AgentAction) GetResourceImpact() *OSResources {
	if x != nil {
		return x.ResourceImpact
	}
	return nil
}

func (x *AgentAction) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentAction) GetReasoningChain() string {
	if x != nil {
		return x.ReasoningChain
	}
	return ""
}

func (x *AgentAction) GetTaskIntent() string {
	if x != nil {
		return x.TaskIntent
	}
	return ""
}

func (x *AgentAction) GetDataSizeBytes() uint64 {
	if x != nil {
		return x.DataSizeBytes
	}
	return 0
}

type ActionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result  *structpb.Struct       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Signal for role evolution (e.g. promote to Boss)
	PromotionSuggested bool `protobuf:"varint,4,opt,name=promotion_suggested,json=promotionSuggested,proto3" json:"promotion_suggested,omitempty"`
	// --- Phase 7: ScheInfer Decision ---
	RoutingProvider string `protobuf:"bytes,5,opt,name=routing_provider,json=routingProvider,proto3" json:"routing_provider,omitempty"` // e.g. "CPU_AVX2", "GPU_CUDA", "GPU_VULKAN"
	// Explicit role enforcement from controller (Task 5.1 cleanup)
	RequiredRole  AgentRole `protobuf:"varint,6,opt,name=required_role,json=requiredRole,proto3,enum=mesh.AgentRole" json:"required_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ActionResponse) GetPromotionSuggested() bool {
	if x != nil {
		return x.PromotionSuggested
	}
	return false
}

func (x *ActionResponse) GetRoutingProvider() string {
	if x != nil {
		return x.RoutingProvider
	}
	return ""
}

func (x *ActionResponse) GetRequiredRole() AgentRole {
	if x != nil {
		return x.RequiredRole
	}
	return AgentRole_OPERATIONAL
}

type InferenceRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentId     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Prompt      string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MaxTokens   uint32                 `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Adaptive Hint: Expected KV Cache size in bytes
	ExpectedKvCacheBytes uint64 `protobuf:"varint,5,opt,name=expected_kv_cache_bytes,json=expectedKvCacheBytes,proto3" json:"expected_kv_cache_bytes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *InferenceRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InferenceRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *InferenceRequest) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *InferenceRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *InferenceRequest) GetExpectedKvCacheBytes() uint64 {
	if x != nil {
		return x.ExpectedKvCacheBytes
	}
	return 0
}

type InferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TokensUsed    uint32                 `protobuf:"varint,2,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	HardwarePath  string                 `protobuf:"bytes,3,opt,name=hardware_path,json=hardwarePath,proto3" json:"hardware_path,omitempty"` // The path chosen by ScheInfer
	LatencyMs     float32                `protobuf:"fixed32,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ThroughputGbs float32                `protobuf:"fixed32,5,opt,name=throughput_gbs,json=throughputGbs,proto3" json:"throughput_gbs,omitempty"`
	Avx512Usage   bool                   `protobuf:"varint,6,opt,name=avx512_usage,json=avx512Usage,proto3" json:"avx512_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *InferenceResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InferenceResponse) GetTokensUsed() uint32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *InferenceResponse) GetHardwarePath() string {
	if x != nil {
		return x.HardwarePath
	}
	return ""
}

func (x *InferenceResponse) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *InferenceResponse) GetThroughputGbs() float32 {
	if x != nil {
		return x.ThroughputGbs
	}
	return 0
}

func (x *InferenceResponse) GetAvx512Usage() bool {
	if x != nil {
		return x.Avx512Usage
	}
	return false
}

type SynthesisRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentIds       []string               `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	TargetGoal     string                 `protobuf:"bytes,2,opt,name=target_goal,json=targetGoal,proto3" json:"target_goal,omitempty"`
	ActionsToMerge []*AgentAction         `protobuf:"bytes,3,rep,name=actions_to_merge,json=actionsToMerge,proto3" json:"actions_to_merge,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SynthesisRequest) Reset() {
	*x = SynthesisRequest{}
	mi := &file_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesisRequest) ProtoMessage() {}

func (x *SynthesisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesisRequest.ProtoReflect.Descriptor instead.
func (*SynthesisRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *SynthesisRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *SynthesisRequest) GetTargetGoal() string {
	if x != nil {
		return x.TargetGoal
	}
	return ""
}

func (x *SynthesisRequest) GetActionsToMerge() []*AgentAction {
	if x != nil {
		return x.ActionsToMerge
	}
	return nil
}

type SynthesisResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SynthesizedState string                 `protobuf:"bytes,1,opt,name=synthesized_state,json=synthesizedState,proto3" json:"synthesized_state,omitempty"`
	ConfidenceScore  float32                `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SynthesisResponse) Reset() {
	*x = SynthesisResponse{}
	mi := &file_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesisResponse) ProtoMessage() {}

func (x *SynthesisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesisResponse.ProtoReflect.Descriptor instead.
func (*SynthesisResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *SynthesisResponse) GetSynthesizedState() string {
	if x != nil {
		return x.SynthesizedState
	}
	return ""
}

func (x *SynthesisResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{10}
}

type MeshStats struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	AgentsActive       int32                    `protobuf:"varint,1,opt,name=agents_active,json=agentsActive,proto3" json:"agents_active,omitempty"`
	AgentLogs          map[string]*AgentMetrics `protobuf:"bytes,2,rep,name=agent_logs,json=agentLogs,proto3" json:"agent_logs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContributionMatrix map[string]*InfluenceMap `protobuf:"bytes,3,rep,name=contribution_matrix,json=contributionMatrix,proto3" json:"contribution_matrix,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MeshStats) Reset() {
	*x = MeshStats{}
	mi := &file_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshStats) ProtoMessage() {}

func (x *MeshStats) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshStats.ProtoReflect.Descriptor instead.
func (*MeshStats) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *MeshStats) GetAgentsActive() int32 {
	if x != nil {
		return x.AgentsActive
	}
	return 0
}

func (x *MeshStats) GetAgentLogs() map[string]*AgentMetrics {
	if x != nil {
		return x.AgentLogs
	}
	return nil
}

func (x *MeshStats) GetContributionMatrix() map[string]*InfluenceMap {
	if x != nil {
		return x.ContributionMatrix
	}
	return nil
}

type AgentMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCalls     uint32                 `protobuf:"varint,1,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	FailedTasks   []string               `protobuf:"bytes,2,rep,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`
	AvgLatencyMs  float32                `protobuf:"fixed32,3,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	TotalTokens   uint32                 `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetrics) Reset() {
	*x = AgentMetrics{}
	mi := &file_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetrics) ProtoMessage() {}

func (x *AgentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetrics.ProtoReflect.Descriptor instead.
func (*AgentMetrics) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *AgentMetrics) GetToolCalls() uint32 {
	if x != nil {
		return x.ToolCalls
	}
	return 0
}

func (x *AgentMetrics) GetFailedTasks() []string {
	if x != nil {
		return x.FailedTasks
	}
	return nil
}

func (x *AgentMetrics) GetAvgLatencyMs() float32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *AgentMetrics) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type InfluenceMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Influence     map[string]float64     `protobuf:"bytes,1,rep,name=influence,proto3" json:"influence,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfluenceMap) Reset() {
	*x = InfluenceMap{}
	mi := &file_mesh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfluenceMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfluenceMap) ProtoMessage() {}

func (x *InfluenceMap) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfluenceMap.ProtoReflect.Descriptor instead.
func (*InfluenceMap) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{13}
}

func (x *InfluenceMap) GetInfluence() map[string]float64 {
	if x != nil {
		return x.Influence
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	MaxResults    int32                  `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_mesh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{14}
}

func (x *SearchRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type SearchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Results          []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ReasoningContext string                 `protobuf:"bytes,2,opt,name=reasoning_context,json=reasoningContext,proto3" json:"reasoning_context,omitempty"` // Contextual relevance from research
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_mesh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{15}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetReasoningContext() string {
	if x != nil {
		return x.ReasoningContext
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // e.g. "Research Paper", "Student-A Log"
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_mesh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{16}
}

func (x *SearchResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_mesh_proto protoreflect.FileDescriptor

const file_mesh_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mesh.proto\x12\x04mesh\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n" +
	"\vOSResources\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x04R\x10memoryTotalBytes\x12 \n" +
	"\fdisk_io_wait\x18\x04 \x01(\x01R\n" +
	"diskIoWait\"\x85\x01\n" +
	"\x10HandshakeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x122\n" +
	"\finitial_role\x18\x03 \x01(\x0e2\x0f.mesh.AgentRoleR\vinitialRole\"\xaf\x01\n" +
	"\x11HandshakeResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12:\n" +
	"\x0fresource_limits\x18\x04 \x01(\v2\x11.mesh.OSResourcesR\x0eresourceLimits\"\xca\x01\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x124\n" +
	"\fcurrent_load\x18\x03 \x01(\v2\x11.mesh.OSResourcesR\vcurrentLoad\x122\n" +
	"\fcurrent_role\x18\x04 \x01(\x0e2\x0f.mesh.AgentRoleR\vcurrentRole\"\xaa\x02\n" +
	"\vAgentAction\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12:\n" +
	"\x0fresource_impact\x18\x03 \x01(\v2\x11.mesh.OSResourcesR\x0eresourceImpact\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x12'\n" +
	"\x0freasoning_chain\x18\x05 \x01(\tR\x0ereasoningChain\x12\x1f\n" +
	"\vtask_intent\x18\x06 \x01(\tR\n" +
	"taskIntent\x12&\n" +
	"\x0fdata_size_bytes\x18\a \x01(\x04R\rdataSizeBytes\"\x83\x02\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12/\n" +
	"\x13promotion_suggested\x18\x04 \x01(\bR\x12promotionSuggested\x12)\n" +
	"\x10routing_provider\x18\x05 \x01(\tR\x0froutingProvider\x124\n" +
	"\rrequired_role\x18\x06 \x01(\x0e2\x0f.mesh.AgentRoleR\frequiredRole\"\xbd\x01\n" +
	"\x10InferenceRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\rR\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x125\n" +
	"\x17expected_kv_cache_bytes\x18\x05 \x01(\x04R\x14expectedKvCacheBytes\"\xd6\x01\n" +
	"\x11InferenceResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vtokens_used\x18\x02 \x01(\rR\n" +
	"tokensUsed\x12#\n" +
	"\rhardware_path\x18\x03 \x01(\tR\fhardwarePath\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x02R\tlatencyMs\x12%\n" +
	"\x0ethroughput_gbs\x18\x05 \x01(\x02R\rthroughputGbs\x12!\n" +
	"\favx512_usage\x18\x06 \x01(\bR\vavx512Usage\"\x8d\x01\n" +
	"\x10SynthesisRequest\x12\x1b\n" +
	"\tagent_ids\x18\x01 \x03(\tR\bagentIds\x12\x1f\n" +
	"\vtarget_goal\x18\x02 \x01(\tR\n" +
	"targetGoal\x12;\n" +
	"\x10actions_to_merge\x18\x03 \x03(\v2\x11.mesh.AgentActionR\x0eactionsToMerge\"k\n" +
	"\x11SynthesisResponse\x12+\n" +
	"\x11synthesized_state\x18\x01 \x01(\tR\x10synthesizedState\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore\"\x0e\n" +
	"\fStatsRequest\"\xf6\x02\n" +
	"\tMeshStats\x12#\n" +
	"\ragents_active\x18\x01 \x01(\x05R\fagentsActive\x12=\n" +
	"\n" +
	"agent_logs\x18\x02 \x03(\v2\x1e.mesh.MeshStats.AgentLogsEntryR\tagentLogs\x12X\n" +
	"\x13contribution_matrix\x18\x03 \x03(\v2'.mesh.MeshStats.ContributionMatrixEntryR\x12contributionMatrix\x1aP\n" +
	"\x0eAgentLogsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.mesh.AgentMetricsR\x05value:\x028\x01\x1aY\n" +
	"\x17ContributionMatrixEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.mesh.InfluenceMapR\x05value:\x028\x01\"\x99\x01\n" +
	"\fAgentMetrics\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\x01 \x01(\rR\ttoolCalls\x12!\n" +
	"\ffailed_tasks\x18\x02 \x03(\tR\vfailedTasks\x12$\n" +
	"\x0eavg_latency_ms\x18\x03 \x01(\x02R\favgLatencyMs\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\rR\vtotalTokens\"\x8d\x01\n" +
	"\fInfluenceMap\x12?\n" +
	"\tinfluence\x18\x01 \x03(\v2!.mesh.InfluenceMap.InfluenceEntryR\tinfluence\x1a<\n" +
	"\x0eInfluenceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"a\n" +
	"\rSearchRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\x05R\n" +
	"maxResults\"k\n" +
	"\x0eSearchResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.mesh.SearchResultR\aresults\x12+\n" +
	"\x11reasoning_context\x18\x02 \x01(\tR\x10reasoningContext\"V\n" +
	"\fSearchResult\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score*+\n" +
	"\tAgentRole\x12\x0f\n" +
	"\vOPERATIONAL\x10\x00\x12\r\n" +
	"\tSTRATEGIC\x10\x012\xd6\x03\n" +
	"\rStrategicMesh\x12@\n" +
	"\rRegisterAgent\x12\x16.mesh.HandshakeRequest\x1a\x17.mesh.HandshakeResponse\x12A\n" +
	"\x16ExecuteStrategicAction\x12\x11.mesh.AgentAction\x1a\x14.mesh.ActionResponse\x12;\n" +
	"\x0eSemanticSearch\x12\x13.mesh.SearchRequest\x1a\x14.mesh.SearchResponse\x12C\n" +
	"\x16GetStateReconstitution\x12\x16.mesh.HandshakeRequest\x1a\x11.mesh.AgentAction\x12D\n" +
	"\x11SynthesizeOutputs\x12\x16.mesh.SynthesisRequest\x1a\x17.mesh.SynthesisResponse\x12C\n" +
	"\x10GenerateResponse\x12\x16.mesh.InferenceRequest\x1a\x17.mesh.InferenceResponse\x123\n" +
	"\fGetMeshStats\x12\x12.mesh.StatsRequest\x1a\x0f.mesh.MeshStatsB.Z,github.com/groovy-byte/agent-mesh-core/protob\x06proto3"

var (
	file_mesh_proto_rawDescOnce sync.Once
	file_mesh_proto_rawDescData []byte
)

func file_mesh_proto_rawDescGZIP() []byte {
	file_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)))
	})
	return file_mesh_proto_rawDescData
}

var file_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_mesh_proto_goTypes = []any{
	(AgentRole)(0),                // 0: mesh.AgentRole
	(*OSResources)(nil),           // 1: mesh.OSResources
	(*HandshakeRequest)(nil),      // 2: mesh.HandshakeRequest
	(*HandshakeResponse)(nil),     // 3: mesh.HandshakeResponse
	(*Heartbeat)(nil),             // 4: mesh.Heartbeat
	(*AgentAction)(nil),           // 5: mesh.AgentAction
	(*ActionResponse)(nil),        // 6: mesh.ActionResponse
	(*InferenceRequest)(nil),      // 7: mesh.InferenceRequest
	(*InferenceResponse)(nil),     // 8: mesh.InferenceResponse
	(*SynthesisRequest)(nil),      // 9: mesh.SynthesisRequest
	(*SynthesisResponse)(nil),     // 10: mesh.SynthesisResponse
	(*StatsRequest)(nil),          // 11: mesh.StatsRequest
	(*MeshStats)(nil),             // 12: mesh.MeshStats
	(*AgentMetrics)(nil),          // 13: mesh.AgentMetrics
	(*InfluenceMap)(nil),          // 14: mesh.InfluenceMap
	(*SearchRequest)(nil),         // 15: mesh.SearchRequest
	(*SearchResponse)(nil),        // 16: mesh.SearchResponse
	(*SearchResult)(nil),          // 17: mesh.SearchResult
	nil,                           // 18: mesh.MeshStats.AgentLogsEntry
	nil,                           // 19: mesh.MeshStats.ContributionMatrixEntry
	nil,                           // 20: mesh.InfluenceMap.InfluenceEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 22: google.protobuf.Struct
}
var file_mesh_proto_depIdxs = []int32{
	0,  // 0: mesh.HandshakeRequest.initial_role:type_name -> mesh.AgentRole
	1,  // 1: mesh.HandshakeResponse.resource_limits:type_name -> mesh.OSResources
	21, // 2: mesh.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 3: mesh.Heartbeat.current_load:type_name -> mesh.OSResources
	0,  // 4: mesh.Heartbeat.current_role:type_name -> mesh.AgentRole
	1,  // 5: mesh.AgentAction.resource_impact:type_name -> mesh.OSResources
	22, // 6: mesh.AgentAction.payload:type_name -> google.protobuf.Struct
	22, // 7: mesh.ActionResponse.result:type_name -> google.protobuf.Struct
	0,  // 8: mesh.ActionResponse.required_role:type_name -> mesh.AgentRole
	5,  // 9: mesh.SynthesisRequest.actions_to_merge:type_name -> mesh.AgentAction
	18, // 10: mesh.MeshStats.agent_logs:type_name -> mesh.MeshStats.AgentLogsEntry
	19, // 11: mesh.MeshStats.contribution_matrix:type_name -> mesh.MeshStats.ContributionMatrixEntry
	20, // 12: mesh.InfluenceMap.influence:type_name -> mesh.InfluenceMap.InfluenceEntry
	17, // 13: mesh.SearchResponse.results:type_name -> mesh.SearchResult
	13, // 14: mesh.MeshStats.AgentLogsEntry.value:type_name -> mesh.AgentMetrics
	14, // 15: mesh.MeshStats.ContributionMatrixEntry.value:type_name -> mesh.InfluenceMap
	2,  // 16: mesh.StrategicMesh.RegisterAgent:input_type -> mesh.HandshakeRequest
	5,  // 17: mesh.StrategicMesh.ExecuteStrategicAction:input_type -> mesh.AgentAction
	15, // 18: mesh.StrategicMesh.SemanticSearch:input_type -> mesh.SearchRequest
	2,  // 19: mesh.StrategicMesh.GetStateReconstitution:input_type -> mesh.HandshakeRequest
	9,  // 20: mesh.StrategicMesh.SynthesizeOutputs:input_type -> mesh.SynthesisRequest
	7,  // 21: mesh.StrategicMesh.GenerateResponse:input_type -> mesh.InferenceRequest
	11, // 22: mesh.StrategicMesh.GetMeshStats:input_type -> mesh.StatsRequest
	3,  // 23: mesh.StrategicMesh.RegisterAgent:output_type -> mesh.HandshakeResponse
	6,  // 24: mesh.StrategicMesh.ExecuteStrategicAction:output_type -> mesh.ActionResponse
	16, // 25: mesh.StrategicMesh.SemanticSearch:output_type -> mesh.SearchResponse
	5,  // 26: mesh.StrategicMesh.GetStateReconstitution:output_type -> mesh.AgentAction
	10, // 27: mesh.StrategicMesh.SynthesizeOutputs:output_type -> mesh.SynthesisResponse
	8,  // 28: mesh.StrategicMesh.GenerateResponse:output_type -> mesh.InferenceResponse
	12, // 29: mesh.StrategicMesh.GetMeshStats:output_type -> mesh.MeshStats
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_mesh_proto_init() }
func file_mesh_proto_init() {
	if File_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_proto_depIdxs,
		EnumInfos:         file_mesh_proto_enumTypes,
		MessageInfos:      file_mesh_proto_msgTypes,
	}.Build()
	File_mesh_proto = out.File
	file_mesh_proto_goTypes = nil
	file_mesh_proto_depIdxs = nil
}
