# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import mesh_pb2 as proto_dot_mesh__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/mesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategicMeshStub(object):
    """--- Strategic Service (gRPC) ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/mesh.StrategicMesh/RegisterAgent',
                request_serializer=proto_dot_mesh__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=proto_dot_mesh__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.ExecuteStrategicAction = channel.unary_unary(
                '/mesh.StrategicMesh/ExecuteStrategicAction',
                request_serializer=proto_dot_mesh__pb2.AgentAction.SerializeToString,
                response_deserializer=proto_dot_mesh__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/mesh.StrategicMesh/SemanticSearch',
                request_serializer=proto_dot_mesh__pb2.SearchRequest.SerializeToString,
                response_deserializer=proto_dot_mesh__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetStateReconstitution = channel.unary_unary(
                '/mesh.StrategicMesh/GetStateReconstitution',
                request_serializer=proto_dot_mesh__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=proto_dot_mesh__pb2.AgentAction.FromString,
                _registered_method=True)
        self.SynthesizeOutputs = channel.unary_unary(
                '/mesh.StrategicMesh/SynthesizeOutputs',
                request_serializer=proto_dot_mesh__pb2.SynthesisRequest.SerializeToString,
                response_deserializer=proto_dot_mesh__pb2.SynthesisResponse.FromString,
                _registered_method=True)
        self.GenerateResponse = channel.unary_unary(
                '/mesh.StrategicMesh/GenerateResponse',
                request_serializer=proto_dot_mesh__pb2.InferenceRequest.SerializeToString,
                response_deserializer=proto_dot_mesh__pb2.InferenceResponse.FromString,
                _registered_method=True)


class StrategicMeshServicer(object):
    """--- Strategic Service (gRPC) ---

    """

    def RegisterAgent(self, request, context):
        """Handshake to enter the mesh
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStrategicAction(self, request, context):
        """Execute high-complexity planning or reasoning tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """Semantic search across shared context and research papers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateReconstitution(self, request, context):
        """Synchronize state for failed node recovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeOutputs(self, request, context):
        """Synthesize parallel agent outputs (AdaptOrch)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateResponse(self, request, context):
        """Phase 8: Hardware-Aware Inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategicMeshServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=proto_dot_mesh__pb2.HandshakeRequest.FromString,
                    response_serializer=proto_dot_mesh__pb2.HandshakeResponse.SerializeToString,
            ),
            'ExecuteStrategicAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteStrategicAction,
                    request_deserializer=proto_dot_mesh__pb2.AgentAction.FromString,
                    response_serializer=proto_dot_mesh__pb2.ActionResponse.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=proto_dot_mesh__pb2.SearchRequest.FromString,
                    response_serializer=proto_dot_mesh__pb2.SearchResponse.SerializeToString,
            ),
            'GetStateReconstitution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateReconstitution,
                    request_deserializer=proto_dot_mesh__pb2.HandshakeRequest.FromString,
                    response_serializer=proto_dot_mesh__pb2.AgentAction.SerializeToString,
            ),
            'SynthesizeOutputs': grpc.unary_unary_rpc_method_handler(
                    servicer.SynthesizeOutputs,
                    request_deserializer=proto_dot_mesh__pb2.SynthesisRequest.FromString,
                    response_serializer=proto_dot_mesh__pb2.SynthesisResponse.SerializeToString,
            ),
            'GenerateResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=proto_dot_mesh__pb2.InferenceRequest.FromString,
                    response_serializer=proto_dot_mesh__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mesh.StrategicMesh', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mesh.StrategicMesh', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategicMesh(object):
    """--- Strategic Service (gRPC) ---

    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.StrategicMesh/RegisterAgent',
            proto_dot_mesh__pb2.HandshakeRequest.SerializeToString,
            proto_dot_mesh__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStrategicAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.StrategicMesh/ExecuteStrategicAction',
            proto_dot_mesh__pb2.AgentAction.SerializeToString,
            proto_dot_mesh__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.StrategicMesh/SemanticSearch',
            proto_dot_mesh__pb2.SearchRequest.SerializeToString,
            proto_dot_mesh__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStateReconstitution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.StrategicMesh/GetStateReconstitution',
            proto_dot_mesh__pb2.HandshakeRequest.SerializeToString,
            proto_dot_mesh__pb2.AgentAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeOutputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.StrategicMesh/SynthesizeOutputs',
            proto_dot_mesh__pb2.SynthesisRequest.SerializeToString,
            proto_dot_mesh__pb2.SynthesisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.StrategicMesh/GenerateResponse',
            proto_dot_mesh__pb2.InferenceRequest.SerializeToString,
            proto_dot_mesh__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
