// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/mesh.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StrategicMesh_RegisterAgent_FullMethodName          = "/mesh.StrategicMesh/RegisterAgent"
	StrategicMesh_ExecuteStrategicAction_FullMethodName = "/mesh.StrategicMesh/ExecuteStrategicAction"
	StrategicMesh_SemanticSearch_FullMethodName         = "/mesh.StrategicMesh/SemanticSearch"
	StrategicMesh_GetStateReconstitution_FullMethodName = "/mesh.StrategicMesh/GetStateReconstitution"
	StrategicMesh_SynthesizeOutputs_FullMethodName      = "/mesh.StrategicMesh/SynthesizeOutputs"
	StrategicMesh_GenerateResponse_FullMethodName       = "/mesh.StrategicMesh/GenerateResponse"
	StrategicMesh_GetMeshStats_FullMethodName           = "/mesh.StrategicMesh/GetMeshStats"
)

// StrategicMeshClient is the client API for StrategicMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategicMeshClient interface {
	// Handshake to enter the mesh
	RegisterAgent(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Execute high-complexity planning or reasoning tasks
	ExecuteStrategicAction(ctx context.Context, in *AgentAction, opts ...grpc.CallOption) (*ActionResponse, error)
	// Semantic search across shared context and research papers
	SemanticSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Synchronize state for failed node recovery
	GetStateReconstitution(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*AgentAction, error)
	// Synthesize parallel agent outputs (AdaptOrch)
	SynthesizeOutputs(ctx context.Context, in *SynthesisRequest, opts ...grpc.CallOption) (*SynthesisResponse, error)
	// Phase 8: Hardware-Aware Inference
	GenerateResponse(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error)
	// Audit & Performance Stats
	GetMeshStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*MeshStats, error)
}

type strategicMeshClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategicMeshClient(cc grpc.ClientConnInterface) StrategicMeshClient {
	return &strategicMeshClient{cc}
}

func (c *strategicMeshClient) RegisterAgent(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, StrategicMesh_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicMeshClient) ExecuteStrategicAction(ctx context.Context, in *AgentAction, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, StrategicMesh_ExecuteStrategicAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicMeshClient) SemanticSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, StrategicMesh_SemanticSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicMeshClient) GetStateReconstitution(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*AgentAction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentAction)
	err := c.cc.Invoke(ctx, StrategicMesh_GetStateReconstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicMeshClient) SynthesizeOutputs(ctx context.Context, in *SynthesisRequest, opts ...grpc.CallOption) (*SynthesisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesisResponse)
	err := c.cc.Invoke(ctx, StrategicMesh_SynthesizeOutputs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicMeshClient) GenerateResponse(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResponse)
	err := c.cc.Invoke(ctx, StrategicMesh_GenerateResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicMeshClient) GetMeshStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*MeshStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeshStats)
	err := c.cc.Invoke(ctx, StrategicMesh_GetMeshStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategicMeshServer is the server API for StrategicMesh service.
// All implementations must embed UnimplementedStrategicMeshServer
// for forward compatibility.
type StrategicMeshServer interface {
	// Handshake to enter the mesh
	RegisterAgent(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Execute high-complexity planning or reasoning tasks
	ExecuteStrategicAction(context.Context, *AgentAction) (*ActionResponse, error)
	// Semantic search across shared context and research papers
	SemanticSearch(context.Context, *SearchRequest) (*SearchResponse, error)
	// Synchronize state for failed node recovery
	GetStateReconstitution(context.Context, *HandshakeRequest) (*AgentAction, error)
	// Synthesize parallel agent outputs (AdaptOrch)
	SynthesizeOutputs(context.Context, *SynthesisRequest) (*SynthesisResponse, error)
	// Phase 8: Hardware-Aware Inference
	GenerateResponse(context.Context, *InferenceRequest) (*InferenceResponse, error)
	// Audit & Performance Stats
	GetMeshStats(context.Context, *StatsRequest) (*MeshStats, error)
	mustEmbedUnimplementedStrategicMeshServer()
}

// UnimplementedStrategicMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategicMeshServer struct{}

func (UnimplementedStrategicMeshServer) RegisterAgent(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedStrategicMeshServer) ExecuteStrategicAction(context.Context, *AgentAction) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteStrategicAction not implemented")
}
func (UnimplementedStrategicMeshServer) SemanticSearch(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SemanticSearch not implemented")
}
func (UnimplementedStrategicMeshServer) GetStateReconstitution(context.Context, *HandshakeRequest) (*AgentAction, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStateReconstitution not implemented")
}
func (UnimplementedStrategicMeshServer) SynthesizeOutputs(context.Context, *SynthesisRequest) (*SynthesisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SynthesizeOutputs not implemented")
}
func (UnimplementedStrategicMeshServer) GenerateResponse(context.Context, *InferenceRequest) (*InferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateResponse not implemented")
}
func (UnimplementedStrategicMeshServer) GetMeshStats(context.Context, *StatsRequest) (*MeshStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeshStats not implemented")
}
func (UnimplementedStrategicMeshServer) mustEmbedUnimplementedStrategicMeshServer() {}
func (UnimplementedStrategicMeshServer) testEmbeddedByValue()                       {}

// UnsafeStrategicMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategicMeshServer will
// result in compilation errors.
type UnsafeStrategicMeshServer interface {
	mustEmbedUnimplementedStrategicMeshServer()
}

func RegisterStrategicMeshServer(s grpc.ServiceRegistrar, srv StrategicMeshServer) {
	// If the following call panics, it indicates UnimplementedStrategicMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StrategicMesh_ServiceDesc, srv)
}

func _StrategicMesh_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicMeshServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicMesh_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicMeshServer).RegisterAgent(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicMesh_ExecuteStrategicAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicMeshServer).ExecuteStrategicAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicMesh_ExecuteStrategicAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicMeshServer).ExecuteStrategicAction(ctx, req.(*AgentAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicMesh_SemanticSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicMeshServer).SemanticSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicMesh_SemanticSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicMeshServer).SemanticSearch(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicMesh_GetStateReconstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicMeshServer).GetStateReconstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicMesh_GetStateReconstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicMeshServer).GetStateReconstitution(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicMesh_SynthesizeOutputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicMeshServer).SynthesizeOutputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicMesh_SynthesizeOutputs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicMeshServer).SynthesizeOutputs(ctx, req.(*SynthesisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicMesh_GenerateResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicMeshServer).GenerateResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicMesh_GenerateResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicMeshServer).GenerateResponse(ctx, req.(*InferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicMesh_GetMeshStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicMeshServer).GetMeshStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicMesh_GetMeshStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicMeshServer).GetMeshStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StrategicMesh_ServiceDesc is the grpc.ServiceDesc for StrategicMesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StrategicMesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mesh.StrategicMesh",
	HandlerType: (*StrategicMeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _StrategicMesh_RegisterAgent_Handler,
		},
		{
			MethodName: "ExecuteStrategicAction",
			Handler:    _StrategicMesh_ExecuteStrategicAction_Handler,
		},
		{
			MethodName: "SemanticSearch",
			Handler:    _StrategicMesh_SemanticSearch_Handler,
		},
		{
			MethodName: "GetStateReconstitution",
			Handler:    _StrategicMesh_GetStateReconstitution_Handler,
		},
		{
			MethodName: "SynthesizeOutputs",
			Handler:    _StrategicMesh_SynthesizeOutputs_Handler,
		},
		{
			MethodName: "GenerateResponse",
			Handler:    _StrategicMesh_GenerateResponse_Handler,
		},
		{
			MethodName: "GetMeshStats",
			Handler:    _StrategicMesh_GetMeshStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mesh.proto",
}
